#!/usr/bin/env python3
"""Build the Codex C-suite leaf agents and packaged team contracts."""

from __future__ import annotations

import argparse
import json
import tempfile
from pathlib import Path
from typing import Any


ADAPTER_PATH = Path("config/harness-adapters/codex.json")
PLUGIN_ROOT = Path("plugins/agi-super-team-codex")
CONTRACTS_PATH = PLUGIN_ROOT / "skills/c-suite-team/references/team-contracts.json"
KIT_REFERENCES_PATH = PLUGIN_ROOT / "skills/c-suite-team/references/kits"
GENERATED_NOTICE = "Generated by scripts/build_codex_csuite_adapter.py; edit config/team-manifest.json instead."


def _json_string(value: str) -> str:
    """A JSON string is also a valid TOML basic string."""

    return json.dumps(value, ensure_ascii=False)


def _leaf_instructions(agent: dict[str, Any]) -> str:
    outputs = ", ".join(agent["outputs"])
    return (
        f"You are the {agent['name']} leaf specialist in an AGI Super Team run. "
        f"Focus: {agent['focus']} Expected outputs: {outputs}. "
        f"Boundary: {agent['boundary']} "
        "Accept one bounded task contract from the parent CEO, inspect only the supplied "
        "evidence and authorized workspace, and return a handoff with artifacts, checks, "
        "limitations, and next action. Do not spawn subagents or coordinate other leaves. "
        "Do not claim runtime verification from structural checks. Never publish, deploy, "
        "trade, contact third parties, use credentials, or take destructive or irreversible "
        "action without explicit human approval. Do not commit, push, merge, or open a PR."
    )


def _render_agent(agent: dict[str, Any]) -> str:
    agent_name = f"ast-{agent['id']}"
    sandbox = "workspace-write" if agent["id"] in {"pe", "cco"} else "read-only"
    description = f"C-suite {agent['id'].upper()} leaf: {agent['focus']}"
    return "\n".join(
        [
            f"# {GENERATED_NOTICE}",
            f"name = {_json_string(agent_name)}",
            f"description = {_json_string(description)}",
            f"nickname_candidates = [{_json_string(agent['id'].upper())}]",
            'model_reasoning_effort = "high"',
            f'sandbox_mode = "{sandbox}"',
            f"developer_instructions = {_json_string(_leaf_instructions(agent))}",
            "",
        ]
    )


def _packaged_contract(manifest: dict[str, Any]) -> dict[str, Any]:
    agent_fields = ("id", "name", "focus", "outputs", "boundary")
    kit_fields = (
        "id",
        "name",
        "outcome",
        "entrypoint",
        "coordinator",
        "reviewers",
        "coreAgents",
        "agents",
        "outputs",
        "checks",
    )
    packaged_kits = []
    for kit in manifest["kits"]:
        packaged_kit = {
            field: kit[field] for field in kit_fields if field in kit
        }
        packaged_kit["entrypoint"] = f"references/kits/{kit['id']}.md"
        packaged_kits.append(packaged_kit)

    return {
        "schemaVersion": manifest["schemaVersion"],
        "generatedFrom": "config/team-manifest.json",
        "runtimeEvidence": "pending",
        "agents": [
            {field: agent[field] for field in agent_fields if field in agent}
            for agent in manifest["agents"]
        ],
        "kits": packaged_kits,
    }


def build_outputs(root: Path) -> dict[Path, str]:
    manifest = json.loads(
        (root / "config/team-manifest.json").read_text(encoding="utf-8")
    )
    leaf_agents = [agent for agent in manifest["agents"] if agent["id"] != "ceo"]
    adapter = {
        "$schema": "./codex.schema.json",
        "schemaVersion": 1,
        "harness": "codex",
        "coordinator": "ceo",
        "independentReviewer": "governor",
        "maxParallelLeaves": 3,
        "fallbackModes": ["native", "manual", "sequential"],
        "runtimeEvidence": "pending",
        "agentMap": {
            agent["id"]: f"ast-{agent['id']}" for agent in leaf_agents
        },
    }
    outputs = {
        root / ADAPTER_PATH: json.dumps(adapter, indent=2, ensure_ascii=False) + "\n",
        root / CONTRACTS_PATH: json.dumps(
            _packaged_contract(manifest), indent=2, ensure_ascii=False
        )
        + "\n",
    }
    for agent in leaf_agents:
        outputs[
            root / PLUGIN_ROOT / "payload/agents" / f"ast-{agent['id']}.toml"
        ] = _render_agent(agent)
    for kit in manifest["kits"]:
        outputs[root / KIT_REFERENCES_PATH / f"{kit['id']}.md"] = (
            root / kit["entrypoint"]
        ).read_text(encoding="utf-8")
    return outputs


def _atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        "w", encoding="utf-8", dir=path.parent, delete=False
    ) as handle:
        handle.write(content)
        temporary = Path(handle.name)
    temporary.replace(path)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    root = arguments.root.resolve()
    outputs = build_outputs(root)
    stale = [
        path
        for path, content in outputs.items()
        if path.is_symlink()
        or not path.is_file()
        or path.read_text(encoding="utf-8") != content
    ]
    expected_agents = {
        path.absolute()
        for path in outputs
        if path.parent == (root / PLUGIN_ROOT / "payload/agents").absolute()
    }
    extra_agents = sorted(
        path
        for path in (root / PLUGIN_ROOT / "payload/agents").glob("ast-*.toml")
        if path.absolute() not in expected_agents
    )
    expected_runbooks = {
        path.absolute()
        for path in outputs
        if path.parent == (root / KIT_REFERENCES_PATH).absolute()
    }
    extra_runbooks = sorted(
        path
        for path in (root / KIT_REFERENCES_PATH).glob("*.md")
        if path.absolute() not in expected_runbooks
    )
    if arguments.check:
        for path in stale:
            print(f"Codex C-suite adapter is stale: {path.relative_to(root)}")
        for path in extra_agents:
            print(f"Unexpected generated C-suite agent: {path.relative_to(root)}")
        for path in extra_runbooks:
            print(f"Unexpected generated Kit runbook: {path.relative_to(root)}")
        return 1 if stale or extra_agents or extra_runbooks else 0
    for path in stale:
        _atomic_write(path, outputs[path])
        print(f"Wrote {path.relative_to(root)}")
    if extra_agents:
        raise RuntimeError(
            "remove obsolete generated agents explicitly: "
            + ", ".join(str(path.relative_to(root)) for path in extra_agents)
        )
    if extra_runbooks:
        raise RuntimeError(
            "remove obsolete generated Kit runbooks explicitly: "
            + ", ".join(str(path.relative_to(root)) for path in extra_runbooks)
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
