#!/usr/bin/env python3
"""Build the reviewed first-party Skill collection from provenance evidence."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


PROVENANCE_PATH = Path("config/skill-provenance.json")
CATALOG_PATH = Path("catalog/skill-index.json")
README_PATH = Path("skills/original/README.md")
INDEX_PATH = Path("skills/original/index.json")


def _load_object(path: Path) -> dict[str, Any]:
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError(f"{path} must contain a JSON object")
    return value


def build_index(root: Path) -> dict[str, Any]:
    provenance = _load_object(root / PROVENANCE_PATH)
    catalog = _load_object(root / CATALOG_PATH)
    catalog_skills = {item["skill_id"]: item for item in catalog["skills"]}
    category_order = {
        item["id"]: position for position, item in enumerate(catalog["categories"])
    }
    category_metadata = {item["id"]: item for item in catalog["categories"]}

    entries: list[dict[str, Any]] = []
    seen: set[str] = set()
    for evidence in provenance["entries"]:
        if not (
            evidence["origin_kind"] == "project-original"
            and evidence["review_state"] == "reviewed"
        ):
            continue
        skill_id = evidence["skill_id"]
        if skill_id in seen:
            raise ValueError(f"duplicate reviewed original Skill: {skill_id}")
        seen.add(skill_id)
        skill_root = root / "skills" / skill_id
        entrypoint = skill_root / "SKILL.md"
        if not entrypoint.is_file() or skill_root.is_symlink():
            raise ValueError(f"reviewed original is not a physical Skill: {skill_id}")
        catalog_entry = catalog_skills.get(skill_id)
        if catalog_entry is None:
            raise ValueError(f"reviewed original is missing from catalog: {skill_id}")
        entries.append(
            {
                "skill_id": skill_id,
                "path": f"skills/{skill_id}/SKILL.md",
                "description": catalog_entry["description"],
                "authors": evidence["authors"],
                "creation_commit": evidence["creation_commit"],
                "category_id": catalog_entry["category_id"],
            }
        )
    entries.sort(key=lambda item: item["skill_id"])

    counts: dict[str, int] = {}
    for entry in entries:
        category_id = entry["category_id"]
        counts[category_id] = counts.get(category_id, 0) + 1
    categories = []
    for category_id in sorted(counts, key=lambda value: category_order[value]):
        metadata = category_metadata[category_id]
        categories.append(
            {
                "id": category_id,
                "name": metadata["title"],
                "emoji": metadata["emoji"],
                "count": counts[category_id],
            }
        )
    return {
        "schemaVersion": 1,
        "scope": "reviewed-project-original-skills",
        "generatedFrom": str(PROVENANCE_PATH),
        "inventoryCount": len(entries),
        "categories": categories,
        "skills": entries,
    }


def render_readme(index: dict[str, Any]) -> str:
    categories = {item["id"]: item for item in index["categories"]}
    by_category: dict[str, list[dict[str, Any]]] = {
        item["id"]: [] for item in index["categories"]
    }
    for entry in index["skills"]:
        by_category[entry["category_id"]].append(entry)

    lines = [
        "<!-- Generated by scripts/build_original_skills_index.py. Do not edit by hand. -->",
        "",
        "# 🌟 Daniel 的原创 Skills",
        "",
        "这里收录经 `config/skill-provenance.json` 审查为 `project-original + reviewed` 的第一方 Skills。",
        "",
        f"当前共 **{index['inventoryCount']}** 个。目录是索引视图；Skill 仍保留在 `skills/<skill-id>/` 的规范位置，避免复制、漂移和重复加载。",
        "",
        "> 原创身份只说明可审计的作者与来源，不代表已经通过生产运行、投资有效性或跨平台兼容性验证。",
        "",
        "候选检索范围与暂不收录原因见 [`CANDIDATE_AUDIT.md`](./CANDIDATE_AUDIT.md)。",
        "",
    ]
    for category in index["categories"]:
        category_id = category["id"]
        lines.extend(
            [
                f"## {category['emoji']} {category['name']}（{category['count']}）",
                "",
            ]
        )
        for entry in by_category[category_id]:
            description = " ".join(str(entry["description"]).split())
            authors = "、".join(entry["authors"])
            lines.append(
                f"- [`{entry['skill_id']}`](../{entry['skill_id']}/) — {description}（作者：{authors}）"
            )
        lines.append("")
    lines.extend(
        [
            "## 收录规则",
            "",
            "- 必须是仓库中存在的物理 Skill，不能是本机软链接。",
            "- 必须有作者、创建提交、许可证和当前树摘要证据。",
            "- 仅有 `author` 字段、提交者身份或旧手写清单不足以自动晋级。",
            "- 外部改编和收集型 Skill 保留在总目录，不进入本原创分类。",
            "",
        ]
    )
    return "\n".join(lines)


def _documents(root: Path) -> dict[Path, str]:
    index = build_index(root)
    return {
        root / INDEX_PATH: json.dumps(index, ensure_ascii=False, indent=2) + "\n",
        root / README_PATH: render_readme(index),
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    root = args.root.resolve()
    documents = _documents(root)
    stale: list[str] = []
    for path, expected in documents.items():
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != expected:
                stale.append(str(path.relative_to(root)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(expected, encoding="utf-8")
    if stale:
        print("stale generated original Skill index: " + ", ".join(stale))
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
