#!/usr/bin/env python3
"""Build deterministic per-Agent Skill indexes from the team manifest."""

from __future__ import annotations

import argparse
import tempfile
from pathlib import Path

from repository_model import load_manifest, physical_skill_names
from skill_evidence import build_evidence_index


GENERATED_MARKER = "<!-- Generated by scripts/build_agent_skill_indexes.py; edit config/team-manifest.json instead. -->"


def _evidence_label(item: dict[str, object]) -> str:
    provenance = item["provenance"]
    curation = item["curation"]
    assert isinstance(provenance, dict) and isinstance(curation, dict)
    origins = {
        "project-original": "项目原创",
        "adapted": "审校改编",
        "collected": "外部收录",
        "unknown": "来源待核",
    }
    origin = origins[str(provenance["origin_kind"])]
    if curation["status"] == "stale":
        score = "内容已变化，评分隐藏"
    elif curation["status"] == "unscored":
        score = "尚未评分"
    else:
        tiers = {
            "exemplary": "典范",
            "recommended": "推荐",
            "selected": "精选",
            "candidate": "候选",
            "hold": "暂缓",
        }
        score = f"{curation['score']}/100 {tiers[str(curation['tier'])]}"
    runtimes = {
        "pending": "待验证",
        "prompt-tested": "已做提示词测试",
        "fixture-one-harness": "已通过单 Harness 夹具",
        "fixture-two-harness": "已通过双 Harness 夹具",
        "external-beta": "已有外部 Beta 证据",
    }
    runtime = runtimes[str(curation["runtime_evidence"])]
    return f"{origin} · {score} · 运行证据：{runtime}"


def _skill_list(skill_ids: list[str], evidence: dict[str, dict[str, object]]) -> list[str]:
    return [
        f"- [`{skill_id}`](../../skills/{skill_id}/) — {_evidence_label(evidence[skill_id])}"
        for skill_id in skill_ids
    ]


def render_agent_index(
    agent: dict[str, object], evidence: dict[str, dict[str, object]]
) -> str:
    """Render one concise, non-authoritative view of an Agent assignment."""

    skills = agent["skills"]
    assert isinstance(skills, dict)
    required = skills["required"]
    optional = skills["optional"]
    harness = skills["harnessSpecific"]
    external = skills["recommendedExternal"]
    outputs = agent["outputs"]
    assert all(isinstance(value, list) for value in (required, optional, harness, external, outputs))

    lines = [
        GENERATED_MARKER,
        "",
        f"# {agent['name']}：专业 Skill 配置",
        "",
        "本页由脚本自动生成，Skill 分配的唯一权威来源是 "
        "[`config/team-manifest.json`](../../config/team-manifest.json)。进入目录只代表结构可发现，"
        "不代表已经过运行验证。",
        "来源、评分与运行证据来自内容摘要匹配的审查记录；缺少证据时会明确显示“来源待核”或“尚未评分”。"
        "详见[评分方法](../../docs/skill-provenance-and-scoring.md)。",
        "",
        "## 🎯 岗位契约",
        "",
        str(agent["focus"]),
        "",
        f"**标准交付物：** {' · '.join(str(item) for item in outputs)}",
        "",
        f"**职责边界：** {agent['boundary']}",
        "",
        "## 🧰 必需核心 Skills",
        "",
        "这些 Skill 构成可移植的 `core` 层；安装器会在写入前验证其物理入口。",
        "",
        *_skill_list(required, evidence),
    ]
    if optional:
        lines.extend(
            [
                "",
                "## 🧪 可选扩展 Skills",
                "",
                "这些 Skill 只在选择 `standard` 层时加入，并在写入前完成存在性检查。",
                "",
                *_skill_list(optional, evidence),
            ]
        )
    if harness:
        lines.extend(
            [
                "",
                "## 🔌 Harness 专属能力",
                "",
                "这些 Skill 依赖特定 Harness、连接器或外部能力；通用安装器不会自动复制或启用。",
                "",
                *_skill_list(harness, evidence),
            ]
        )
    if external:
        lines.extend(
            [
                "",
                "## 🌐 外部候选",
                "",
                "这些标识只用于发现候选，本仓库未打包、未验证，也不会自动安装。",
                "",
                *[f"- `{skill_id}`" for skill_id in external],
            ]
        )
    lines.extend(
        [
            "",
            "## ✅ 调用与审批规则",
            "",
            "1. 只加载能完成当前结果的最小 Skill 集合。",
            "2. 调用前阅读所选 `SKILL.md`、关联资源、权限要求与限制。",
            "3. 发布、凭据、资金、部署、生产写入或破坏性动作必须获得人类明确批准。",
            "4. 在交接中记录产物、验证证据、证据时效和未解决限制。",
            "",
            "需要替代方案时，浏览完整的[生成式 Skill 目录](../../catalog/)。",
            "",
        ]
    )
    return "\n".join(lines)


def build_outputs(root: Path) -> dict[Path, str]:
    manifest = load_manifest(root)
    canonical_skills = physical_skill_names(root)
    evidence = build_evidence_index(root)
    outputs: dict[Path, str] = {}
    for agent in manifest["agents"]:
        local_assignments = []
        for level in ("required", "optional", "harnessSpecific"):
            local_assignments.extend(agent["skills"][level])
        missing = sorted(set(local_assignments) - canonical_skills)
        if missing:
            raise ValueError(f"{agent['id']} references missing local Skills: {', '.join(missing)}")
        target = root / agent["path"] / "TOOLS.md"
        outputs[target] = render_agent_index(agent, evidence)
    return outputs


def _atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        "w", encoding="utf-8", dir=path.parent, delete=False
    ) as handle:
        handle.write(content)
        temporary = Path(handle.name)
    temporary.replace(path)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    root = arguments.root.resolve()
    outputs = build_outputs(root)

    stale = [path for path, content in outputs.items() if not path.is_file() or path.read_text(encoding="utf-8") != content]
    if arguments.check:
        if stale:
            for path in stale:
                print(f"Agent Skill index is stale: {path.relative_to(root)}")
            return 1
        print(f"Agent Skill indexes are current: {len(outputs)}")
        return 0

    for path in stale:
        _atomic_write(path, outputs[path])
        print(f"Wrote {path.relative_to(root)}")
    if not stale:
        print(f"Agent Skill indexes already current: {len(outputs)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
